spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: "LeHZCsI6rEqwPGhEtjpIlHN7dxsNg3dTmRqPqUjznwQFHLD5tQwbgKH2cQETnfQo"

#    https://passwords-generator.org/kr/ 사이트에서 크기 64로 생성

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
